const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  home: () => ipcRenderer.invoke('home'),
  playlistDetail: (id) => ipcRenderer.invoke('playlist-detail', id),
  likedSongs: (userId) => ipcRenderer.invoke('liked-songs', userId),
  likedSongsCached: (userId) => ipcRenderer.invoke('liked-songs-cached', userId),
  likedSummary: (userId) => ipcRenderer.invoke('liked-summary', userId),
  fm: () => ipcRenderer.invoke('fm'),
  fetchCover: (url) => ipcRenderer.invoke('fetch-cover', url),
  search: (kw, platform) => ipcRenderer.invoke('search', kw, platform),
  resolveUrl: (id, level, platform) => ipcRenderer.invoke('resolve-url', id, level, platform),
  lyricFast: (id, platform, extra) => ipcRenderer.invoke('lyric-fast', id, platform, extra),
  lyric: (id, platform, extra) => ipcRenderer.invoke('lyric', id, platform, extra),
  qqHome: () => ipcRenderer.invoke('qq-home'),
  qqPlaylistDetail: (id) => ipcRenderer.invoke('qq-playlist-detail', id),
  qqLiked: () => ipcRenderer.invoke('qq-liked'),
  qqLikeSong: (mid, like) => ipcRenderer.invoke('qq-like-song', mid, like),
  qqLikeStatus: (ids) => ipcRenderer.invoke('qq-like-status', ids),
  openLogin: () => ipcRenderer.invoke('open-login'),
  loginEmbedStart: (platform) => ipcRenderer.invoke('login-embed-start', platform),
  loginEmbedStop: (platform) => ipcRenderer.invoke('login-embed-stop', platform),
  qqEmbedOpen: () => ipcRenderer.invoke('qq-embed-open'),
  qqEmbedClose: () => ipcRenderer.invoke('qq-embed-close'),
  onQqEmbedClosed: (cb) => ipcRenderer.on('qq-embed-closed', () => cb()),
  ncmQrStart: () => ipcRenderer.invoke('ncm-qr-start'),
  ncmQrCheck: (unikey) => ipcRenderer.invoke('ncm-qr-check', unikey),
  getLoginState: () => ipcRenderer.invoke('get-login-state'),
  logout: () => ipcRenderer.invoke('logout'),
  setCookie: (text) => ipcRenderer.invoke('set-cookie', text),
  onLoginSuccess: (cb) => ipcRenderer.on('login-success', (_e, nickname, userId) => cb(nickname, userId)),
  qqSearch: (kw) => ipcRenderer.invoke('qq-search', kw),
  qqResolveUrl: (songmid, level) => ipcRenderer.invoke('qq-resolve-url', songmid, level),
  qqLyric: (songmid) => ipcRenderer.invoke('qq-lyric', songmid),
  qqLoginState: () => ipcRenderer.invoke('qq-login-state'),
  qqOpenLogin: () => ipcRenderer.invoke('qq-open-login'),
  qqLogout: () => ipcRenderer.invoke('qq-logout'),
  onQqLoginSuccess: (cb) => ipcRenderer.on('qq-login-success', (_e, nickname, userId, avatar) => cb(nickname, userId, avatar)),
  toggleLyricWindow: () => ipcRenderer.invoke('toggle-lyric-window'),
  sendLyricLine: (data) => ipcRenderer.send('lyric-line', data),
  likeSong: (id, like) => ipcRenderer.invoke('like-song', id, like),
  likeStatus: (ids) => ipcRenderer.invoke('like-status', ids),
  openSongPage: (id) => ipcRenderer.invoke('open-song-page', id),
  aiTest: (cfg) => ipcRenderer.invoke('ai-test', cfg),
  aiChat: (cfg, messages) => ipcRenderer.invoke('ai-chat', cfg, messages),
  aiMusicContext: () => ipcRenderer.invoke('ai-music-context'),
  onMediaCommand: (cb) => ipcRenderer.on('media-command', (_e, cmd) => cb(cmd)),
  toggleMini: () => ipcRenderer.invoke('toggle-mini'),
  sendMiniState: (data) => ipcRenderer.send('mini-state', data),
  onMiniClosed: (cb) => ipcRenderer.on('mini-closed', () => cb()),
  winMin: () => ipcRenderer.invoke('win-min'),
  winMax: () => ipcRenderer.invoke('win-max'),
  winClose: () => ipcRenderer.invoke('win-close'),
  onMaximized: (cb) => ipcRenderer.on('window-maximized', (_e, isMax) => cb(isMax)),
  updateCheck: () => ipcRenderer.invoke('update-check'),
  updateDownload: () => ipcRenderer.invoke('update-download'),
  updateInstall: () => ipcRenderer.invoke('update-install'),
  onAppUpdate: (cb) => ipcRenderer.on('app-update', (_e, data) => cb(data)),
  setTrayLyricState: (on) => ipcRenderer.send('tray-lyric-state', on),
  listWallpapers: () => ipcRenderer.invoke('list-wallpapers'),
  wallpaperEngineInfo: () => ipcRenderer.invoke('wallpaper-engine-info'),
  weActiveWallpaper: () => ipcRenderer.invoke('we-active-wallpaper')
});
