const fs = require('fs');
const path = require('path');
const base = path.join(__dirname, '..', 'renderer', 'src', 'mr');
const files = [
  '00-core-stores.js',
  '04-fx-defaults.js',
  '05-packaged-fx-archive.js',
  '01-orbit-free-camera.js',
  '03-focus-cinema-camera.js',
  '00-pointer-cover-particles.js',
  '01-float-skull-backcover.js',
  '02-lyrics-state-layout.js',
  '03-lyrics-star-river.js',
  '04-visual-settings-persistence.js',
  '05-lyrics-fonts-texture.js',
  '06-custom-background-colorlab.js',
  '07-lyrics-palette-text-utils.js',
  '08-lyrics-display-modes.js',
  '09-lyrics-payloads.js',
  '10-lyrics-mask-textures.js',
  '11-lyrics-shaders.js',
  '12-lyrics-row-layers.js',
  '13-lyrics-mesh-build.js',
  '14-stage-lyrics-rendering.js',
  '15-ripples-cover-depth.js',
  'sonic-topography-preset.js',
  'sonic-workshop-preset.js',
  '00-preset-archive-data.js',
  '04-preset-grid-uniforms.js',
];
const arr = files.map((f) => fs.readFileSync(path.join(base, f), 'utf8'));
const out = '// Auto-generated by scripts/gen-mr-data.js — do not edit by hand.\n' +
  '// Mineradio (GPL-3.0) stage sources embedded as JSON strings to avoid esbuild `?raw` issues.\n' +
  'export const MR_SOURCES = ' + JSON.stringify(arr) + ';\n';
fs.writeFileSync(path.join(__dirname, '..', 'renderer', 'src', 'mr-stage-data.js'), out);
console.log('Wrote mr-stage-data.js, bytes =', out.length, 'files =', files.length);
